# import required module
from PIL import Image
import glob
from tanggal import thnskr, bulanangka, bulan, bsk
  
folderNDF = ("D:/TAHUN "+thnskr+"/"+str (bulanangka)+". "+bulan+"/NDF/"+bsk+"/")
######### Crop
asmat = Image.open(folderNDF+"asmat.png").crop((0, 0, 744, 609)).save(folderNDF+"asmat.png")
biak = Image.open(folderNDF+"biak.png").crop((0, 0, 744, 960)).save(folderNDF+"biak.png")
bintang1 = Image.open(folderNDF+"bintang1.png").crop((0, 0, 744, 928)).save(folderNDF+"bintang1.png")
bintang2 = Image.open(folderNDF+"bintang2.png").crop((0, 0, 744, 898)).save(folderNDF+"bintang2.png")
boven = Image.open(folderNDF+"boven.png").crop((0, 0, 744, 1052)).save(folderNDF+"boven.png")
deiyai = Image.open(folderNDF+"deiyai.png").crop((0, 0, 744, 574)).save(folderNDF+"deiyai.png")
dogiyai = Image.open(folderNDF+"dogiyai.png").crop((0, 0, 744, 670)).save(folderNDF+"dogiyai.png")
intan = Image.open(folderNDF+"intan.png").crop((0, 0, 744, 610)).save(folderNDF+"intan.png")
jayawijaya = Image.open(folderNDF+"jayawijaya.png").crop((0, 0, 744, 832)).save(folderNDF+"jayawijaya.png")
jprkab = Image.open(folderNDF+"jprkab.png").crop((0, 0, 744, 929)).save(folderNDF+"jprkab.png")
jprkota = Image.open(folderNDF+"jprkota.png").crop((0, 0, 744, 581)).save(folderNDF+"jprkota.png")
keerom = Image.open(folderNDF+"keerom.png").crop((0, 0, 744, 612)).save(folderNDF+"keerom.png")
lanny = Image.open(folderNDF+"lanny.png").crop((0, 0, 744, 673)).save(folderNDF+"lanny.png")
mamberaya = Image.open(folderNDF+"mamberaya.png").crop((0, 0, 744, 548)).save(folderNDF+"mamberaya.png")
mamteng = Image.open(folderNDF+"mamteng.png").crop((0, 0, 744, 644)).save(folderNDF+"mamteng.png")
mappi = Image.open(folderNDF+"mappi.png").crop((0, 0, 744, 741)).save(folderNDF+"mappi.png")
merauke = Image.open(folderNDF+"merauke.png").crop((0, 0, 744, 1052)).save(folderNDF+"merauke.png")
mimika = Image.open(folderNDF+"mimika.png").crop((0, 0, 744, 803)).save(folderNDF+"mimika.png")
nabire = Image.open(folderNDF+"nabire.png").crop((0, 0, 744, 867)).save(folderNDF+"nabire.png")
ndunga = Image.open(folderNDF+"ndunga.png").crop((0, 0, 744, 646)).save(folderNDF+"ndunga.png")
paniai = Image.open(folderNDF+"paniai.png").crop((0, 0, 744, 613)).save(folderNDF+"paniai.png")
puncak = Image.open(folderNDF+"puncak.png").crop((0, 0, 744, 772)).save(folderNDF+"puncak.png")
sarmi = Image.open(folderNDF+"sarmi.png").crop((0, 0, 744, 677)).save(folderNDF+"sarmi.png")
supiori = Image.open(folderNDF+"supiori.png").crop((0, 0, 744, 549)).save(folderNDF+"supiori.png")
toli1 = Image.open(folderNDF+"toli1.png").crop((0, 0, 744, 961)).save(folderNDF+"toli1.png")
toli2 = Image.open(folderNDF+"toli2.png").crop((0, 0, 744, 962)).save(folderNDF+"toli2.png")
waropen = Image.open(folderNDF+"waropen.png").crop((0, 0, 744, 518)).save(folderNDF+"waropen.png")
yahu1 = Image.open(folderNDF+"yahu1.png").crop((0, 0, 744, 962)).save(folderNDF+"yahu1.png")
yahu2 = Image.open(folderNDF+"yahu2.png").crop((0, 0, 744, 962)).save(folderNDF+"yahu2.png")
yahu3 = Image.open(folderNDF+"yahu3.png").crop((0, 0, 744, 931)).save(folderNDF+"yahu3.png")
yalimo = Image.open(folderNDF+"yalimo.png").crop((0, 0, 744, 581)).save(folderNDF+"yalimo.png")
yapen = Image.open(folderNDF+"yapen.png").crop((0, 0, 744, 805)).save(folderNDF+"yapen.png")