# Generated by Selenium IDE
from lib2to3.pgen2 import driver
#from typing_extensions import Self
import pytest
import time
import json
import pickle
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Whatsapp():
  def setup_method(self, method):
    Option = Options()
    Option.add_argument = {'user-data-dir':'/Users/arifr/AppData/Local/Google/Chrome/User Data/Profile 2'}
    self.driver = webdriver.Chrome("C:/Coding/R/Ripcy/chromedriver.exe", options=Option)
    
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1(self):
    # Test name: 1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://web.whatsapp.com/")
    # 2 | setWindowSize | 1920x1080 | 
    self.driver.set_window_size(1920, 1080)
    self.driver.get_cookies()
    # 3 | click | css=.\_2_TVt .\_3vPI2 .ggj6brxn | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2_TVt .\\_3vPI2 .ggj6brxn").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | mouseOver | linkText=https://web.whatsapp.com/ | 
    element = self.driver.find_element(By.LINK_TEXT, "https://web.whatsapp.com/")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | linkText=https://web.whatsapp.com/ | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | css=.fd365im1 > .selectable-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".fd365im1 > .selectable-text").click()
    # 8 | editContent | css=.fd365im1 | <p class="selectable-text copyable-text" dir="ltr"><span class="selectable-text copyable-text" data-lexical-text="true">Tes1</span></p>
    element = self.driver.find_element(By.CSS_SELECTOR, ".fd365im1")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p class=\"selectable-text copyable-text\" dir=\"ltr\"><span class=\"selectable-text copyable-text\" data-lexical-text=\"true\">Tes1</span></p>'}", element)
    # 9 | click | css=.svlsagor > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".svlsagor > span").click()
  
WA = Whatsapp()

WA.setup_method("")
WA.test_1()
WA.teardown_method("")