# Generated by Selenium IDE
import time
import json
import pickle
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities



from io import BytesIO
import win32clipboard
from PIL import Image


def send_to_clipboard(clip_type, data):
    win32clipboard.OpenClipboard()
    win32clipboard.EmptyClipboard()
    win32clipboard.SetClipboardData(clip_type, data)
    win32clipboard.CloseClipboard()

filepath = 'Ico2.png'
image = Image.open("D:/TAHUN 2022/9. SEPTEMBER/NDF/11092022/kabupaten.png")

output = BytesIO()
image.convert("RGB").save(output, "BMP")
data = output.getvalue()[14:]
output.close()

send_to_clipboard(win32clipboard.CF_DIB, data)

driver = webdriver.Chrome("C:/Ripcy/Script_1/Ripcy-1/chromedriver.exe")
driver.get("https://twitter.com/")
cookies = pickle.load(open("twitter.pkl", "rb"))
for cookie in cookies:
  cookie['domain'] = ".twitter.com"

  try:
    driver.add_cookie(cookie)
  except Exception as e:
    print(e)
driver.get("https://twitter.com/home")
driver.set_window_size(922, 1032)
driver.find_element(By.CSS_SELECTOR, ".r-1472mwg").click()
time.sleep(2)
paste = driver.find_element(By.XPATH, '//*[@id="layers"]/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/div/div[3]/div/div[1]/div/div/div/div/div[2]/div[1]/div/div/div/div/div/div[2]/div/div/div/div/label/div[1]/div/div/div/div/div/div[2]/div')
time.sleep(2)
paste.send_keys("", Keys.CONTROL, 'v')

driver.find_element(By.CSS_SELECTOR, ".css-18t94o4:nth-child(4) > .css-901oao > .css-901oao > .css-901oao").click()

