# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://twitter.com/home")
    self.driver.set_window_size(922, 1032)
    self.driver.find_element(By.CSS_SELECTOR, ".r-1472mwg").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .css-1dbjc4n:nth-child(1) > .css-1dbjc4n:nth-child(1) > .css-1dbjc4n:nth-child(1) > .css-1dbjc4n:nth-child(1) > .css-1dbjc4n:nth-child(2) > div:nth-child(3) .css-1dbjc4n:nth-child(1) > .css-18t94o4:nth-child(1) > .css-901oao:nth-child(1) > .r-1cvl2hr:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".css-18t94o4:nth-child(4) > .css-901oao > .css-901oao > .css-901oao").click()
  
